"""empty message

Revision ID: 1a68d6966d55
Revises: 00e523bfafc6
Create Date: 2018-10-24 16:40:32.361488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a68d6966d55'
down_revision = '00e523bfafc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.create_index(op.f('ix_Posts_timestamp'), 'Posts', ['timestamp'], unique=False)
    op.drop_index('ix_Posts_timestamp', table_name='Posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Posts_timestamp', 'Posts', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_Posts_timestamp'), table_name='Posts')
    op.drop_column('Posts', 'body_html')
    # ### end Alembic commands ###
