"""empty message

Revision ID: 41abb6d63e4e
Revises: 07b9c71ddd8e
Create Date: 2018-10-01 14:34:00.808868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abb6d63e4e'
down_revision = '07b9c71ddd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
