"""empty message

Revision ID: 545b4b87ac23
Revises: 83d637a917ab
Create Date: 2018-10-03 14:26:36.050806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545b4b87ac23'
down_revision = '83d637a917ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
